server:
    port: 8080
    servlet:
        context-path:

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/e_learning"
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    signerKey: "sDd3tkGGcBWFeKUZsqBgXGPx/dkcXehI8WcYobvUW1T7tLqgVsFHXDPotVIK2TL/"
    valid-duration: 60 #in seconds
    refreshable-duration: 120 #in seconds